### ISSUE TITLE
Test (and deploy?) updated client

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-client#22]
Test here: http://eosdac.dacfactory.io/

Main thing we have to test is that the custodian stake works as expected. We have to update contracts before deploying new client. Also need to test the proposal for transfers.

### Roadmap

- [x] Clean up the how it works page
- [ ] clarify the steps for bringing your own token
- [ ] They are familiar with DACs, but not the DAC Factory
- [ ] Deploy contracts
- [ ] Michael does token migration
- [ ] Update client, create release tag
- [ ] Deploy client
- [ ] Create msig for custodians to sign which will transfer stake to custodians. This will increase their vote weight as well.

**Comment by str** [comment]
https://members.eosdac.io is not working. And it looks http://eosdac.dacfactory.io is the one working fine.    Is this temporary? Should  members.eosdac redirect to eosdac.dacfactory? Or the other way around?  What does this mean for future DACs? Will they all have their custom domain, or will they all use dacfactory.io subdomain?

Should we have HTTPS?

**Comment by str** [comment]
@michaeljyeates  will release to  https://members.eosdac.io/
